//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppRemax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Houses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Houses()
        {
            this.Images = new HashSet<Images>();
        }
    
        public int refHouse { get; set; }
        public int referBuildingType { get; set; }
        public int referNumBedrooms { get; set; }
        public int referNumParking { get; set; }
        public int referPropertyType { get; set; }
        public double price { get; set; }
        public int referEmployee { get; set; }
        public int referClient { get; set; }
        public Nullable<bool> Pool { get; set; }
        public Nullable<bool> Waterfront { get; set; }
        public Nullable<bool> Elevator { get; set; }
        public Nullable<bool> Reduced_mobility { get; set; }
        public int NetArea { get; set; }
        public int YearBuilt { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    
        public virtual BuildingType BuildingType { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual NumBedrooms NumBedrooms { get; set; }
        public virtual NumParking NumParking { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
    }
}
