//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppRemax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int refMessage { get; set; }
        public string Message { get; set; }
        public Nullable<int> referAgent { get; set; }
        public Nullable<System.TimeSpan> Date { get; set; }
        public string SenderEmail { get; set; }
        public string SenderPhone { get; set; }
        public string SenderName { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
