//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppRemax
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewHouses
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Year { get; set; }
        public int NetArea { get; set; }
        public double Price { get; set; }
        public string Building { get; set; }
        public string Bedrooms { get; set; }
        public string Parking { get; set; }
        public string Property { get; set; }
        public string Agent { get; set; }
        public string Seller { get; set; }
        public Nullable<bool> Pool { get; set; }
        public Nullable<bool> Water { get; set; }
        public Nullable<bool> Mobility { get; set; }
        public Nullable<bool> Elevator { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
    }
}
